### ISSUE TITLE
Lags on multiple buffer change

### ISSUE THREAD

**Issue by faceleg** [vim-utils/vim-troll-stopper#2]
Background: http://vi.stackexchange.com/questions/5316/fixing-lag-due-to-vim-troll-stopper-plugin

**Comment by bruno-** [comment]
Hi,
we tried to address this in #1. This helped with the speed, but then we had some issues where the plugin didn't highlight "troll" chars. Namely with `BufRead,BufNewFile`, tests 1. and 3. described [here](https://github.com/vim-utils/vim-troll-stopper/blob/8a53b5b5bf26a070419ccaf9cbfccc6cf6cb7cfc/plugin/troll_stopper.vim#L318-L324) failed.

Now I see the problem still persists. This seems to be a hard problem to nail it right for every scenario.

**Comment by bruno-** [comment]
Hi @faceleg,
I identified the problem and pushed 50faf52ada98070cfec28b679f521579ad82a948.

Can you pull the newest plugin version and check if the problem still persists? Thanks.

**Comment by bruno-** [comment]
Here's a more thorough [answer](http://vi.stackexchange.com/a/5334/345) to the `vi.stackexchange` question from the first post.

**Comment by faceleg** [comment]
Pulling it now, will use it throughout the day and report back

**Comment by faceleg** [comment]
Looks good to me, the problem would have shown itself by now.

Thanks!

**Comment by bruno-** [comment]
Great @faceleg, thanks for testing and confirming things are good now!

**Comment by faceleg** [comment]
:dancer:
